### ISSUE TITLE
Error on running radiergummi.py

### ISSUE THREAD

**Issue by xvrII** [ilf/twitter-eraser#1]
Hey, can you please help me here? I get this error, and I think I've follow all the procedures. 
Thanks. 

xvrIl@xvrII-KSD:~/tweetdeleter$ python2.7 radiergummi.py
Traceback (most recent call last):
  File "radiergummi.py", line 25, in <module>
    api.destroy_status(status.id)
  File "/usr/lib/python2.7/dist-packages/tweepy/binder.py", line 197, in _call
    return method.execute()
  File "/usr/lib/python2.7/dist-packages/tweepy/binder.py", line 173, in execute
    raise TweepError(error_msg, resp)
tweepy.error.TweepError: Read-only application cannot POST.

**Comment by ilf** [comment]
The message "Read-only application cannot POST" sounds like you need to change your App permissions to "Read, Write and Access direct messages" in https://apps.twitter.com/

**Comment by xvrII** [comment]
Oh, well. Thanks. I had to regenerate the Token in order to reset permissions. It runned. However, it didn't do much. It said it deleted like 20 updates, but I don't see what it deleted... I'm afraid it is not working...

However, I deleted the part of the file refered to favorites and direct messages, I don't want to delete those. That shouldn't affect the deletion of updates, right? 

Don't know what to say or do, it runs, but don't work. :(

**Comment by ilf** [comment]
It's kind of hard to understand the problem without more details or errors. Is there an error message?
Have you let it run multiple times? Are you checking your feed on the website, not in a client that might use its cache?

Yes, deleting the parts for favs and DMs should be okay.

**Comment by xvrII** [comment]
Thanks for the answer. Yes, I run it many times and I check it on twitter.com. 
There is no error message, it just runs and does nothing. Somedays it deletes like 40 tweets, but just that. 
Maybe it's some limitation in the twitter app.

**Comment by ilf** [comment]
This is (was?) an issue with Twitters API, not this script.
